### ISSUE TITLE
To divide library and sample

### ISSUE THREAD

**Issue by kochizufan** [charlenni/OsmSharp.Forms#1]
Hi,
Thank you for great working.

This is not this repo.'s issue, but it is happy if you give me some advise ...

This repo's project combine library code and sample code, so I try to divide them in my repo,

https://github.com/tilemapjp/OsmSharp.Forms/tree/devide_library_sample

But, it works well in Android, but in iOS, both online tile and offline db are not loaded, and displaying whiteout view.
Error is not occurred.
I can't understand why it is...

Would you please give some advise to me?
Or, would you please give official sample for dividing library and sample project?

Regards,
Kohei

**Comment by charlenni** [comment]
OsmSharp.Forms implementation is only an example, how to do this. I do not support this anymore, because I encountered some problems of OsmSharp. One of this problems is the offline map. To use it, OsmSharp always read the whole .osm/.osm.pbf file into memory. With small files, like only one town, it works, but if the map files is bigger, than you get an out of memory error, and the whole process is very slow. Even the online tiles are sometimes very slow.

But I refactored the repository and tested it again. Now you have a extra demo project. Works on Android and iOS. If your system isn't very fast, you should wait some time, if you press the "offline" button. It takes even on the iOS emulator over 5 s (for the 3 MB test file). So be patient and be carefull not to press the button to fast again.

**Comment by kochizufan** [comment]
I see, thank you!
And you looks active in developing MapsForgeSharp... you feel MapsForge is better than OsmSharp?
If so, I will try it.

**Comment by charlenni** [comment]
You are right. Because I couldn't get up OsmSharp with offline maps, I looked around and found Mapsforge. Mapsforge is more than a control, it's a file format too. I started with converting the Java code to C#. As graphical engine I use SkiaSharp. Up to now I could load .map files in Mapsforge format and style files in mapcss format. With both it is possible to draw tiles without labels. Labels a little bit difficult, because labels could be on more than one tile.

There isn't any map control to use. There is much work to do. I thought, that it could be possible to use Mapsforge as a simple tile provider, which could draw the tiles and display them with the existing map controls (Google Maps, MKMapKit and so on).

You are welcome to work with us on this project.
